version: "3.8"
  
services:
  mongodb:
    image : mongo
    container_name: mongodb
    ports:
    - 27017:27017
    healthcheck:
      test:
      - CMD
      - mongo
      - --eval
      - "db.adminCommand('ping')"
    restart: unless-stopped
  
  appdocapi:
    build:
      context: .
      dockerfile: ./dockerfile
    ports: 
      - 8080:8080
    restart: on-failure
    env_file:
       - .env
    depends_on:
      mongodb:
        condition: service_healthy